language: node_js

cache: yarn

install:
- yarn global add travis-ci-cloudfront-invalidation
- yarn

script:
- yarn ci || travis_terminate 1
- yarn build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  bucket: st6-meme
  upload_dir: meme
  local_dir: build
  skip_cleanup: true
  on:
    branch: master

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_ID -c $CF_DISTRIBUTION_ID -i '/meme/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
